apiVersion: apps/v1
kind: Deployment
metadata:
   name: webapp
spec:
   selector:
     matchLabels:
        app: webapp
   replicas: 1
   template:
      metadata: 
        labels:
          app: webapp
      spec:
        containers:
         - name: webapp
           image: richardchesterwood/k8s-fleetman-webapp-angular:release1
           env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice


---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
   selector:
     app: webapp
   ports:
    - name: http
      port: 80
      nodePort: 30050
   type: NodePort
